### DISCUSSION TITLE
KaTeX web responsive style for small screened devices (with scroll bar)

### DISCUSSION THREAD

**Discussion by toshikijp** [andatoshiki/toshiki-discuss#23] [Q&A] [answered]
see #3

**Comment by andatoshiki** [comment, marked as answer]
```css
.katex-display > .katex {
  display: inline-block;
  white-space: nowrap;
  max-width: 100%;
  overflow-x: scroll;
  text-align: initial;
}
.katex {
  font: normal 1.21em KaTeX_Main, Times New Roman, serif;
  line-height: 1.2;
  white-space: normal;
  text-indent: 0;
}
```
